# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bucketphone112"
    encrypt        = true
    key            = "lambda/terraform"
    region         = "us-east-1"
  }
}
